services:
  - type: web
    name: to-score-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        generateValue: false

  - type: web
    name: to-score-finance
    runtime: python
    buildCommand: pip install -r finance/requirements.txt
    startCommand: python finance/src/dashboard.py
    envVars:
      - key: PORT
        generateValue: false
